#!/bin/bash
if [ -f /sys/hypervisor/uuid ] && [ `head -c 3 /sys/hypervisor/uuid` == ec2 ]; then
  export AWS_EC2=1
  export AWS_IT="$(wget -q -O - http://169.254.169.254/latest/meta-data/instance-type)"
else
  export AWS_EC2=0
fi


function getCost() {
  ./getCost.sh
}; export -f getCost
