#a Aliases
alias ll='ls -alF'
alias rm='rm -i'
alias cp='cp -rfv'
alias du='du -h'
alias df='df -h'
alias less='less -r'
alias path='echo -e ${PATH//:/\\n}'
alias openports='netstat -tulanp'
alias wget='wget -c'
alias grep='grep --color=auto --exclude-dir="*.svn" --exclude-dir="*.git"'
alias tmuxs='tmux_sixel -L tmux_sixel'
alias mytop='HTOPRC=${SC_HTOPRC} htop'
alias k='kubectl'
