#a Aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias rm='rm -i'
alias cp='cp -rfv'
alias ls='ls -hF'
alias du='du -h'
alias df='df -h'
alias less='less -r'
alias path='echo -e ${PATH//:/\\n}'
alias openports='netstat -tulanp'
alias wget='wget -c'
alias grep='grep --color=auto --exclude-dir="*.svn" --exclude-dir="*.git"'
alias be_sd='sudo -i -u "sysdev" script /dev/null'
alias sysdev='sudo -i -u "sysdev" script /dev/null'
alias tmuxs='tmux_sixel -L tmux_sixel'
alias mytop='HTOPRC=${SC_HTOPRC} htop'
